accounts/urls.py
from django.urls import path
from django.contrib.auth.views import LogoutView

from .views import LoginView, RegisterView

app_name = 'accounts'

urlpatterns = [
    path('login/', LoginView.as_view(), name='login'),
    path('register/', RegisterView.as_view(), name='register'),
    path('logout/', LogoutView.as_view(), name='logout'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('movies.urls')),
    path('accounts/', include('accounts.urls')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

movies/urls.py
from django.urls import path

from .views import (
    HomePageView,
    MovieDetailView,
    CommentCreateView,
    BrowseMoviesListView,
    NoPiracyTemplateView)

app_name = 'movies'

urlpatterns = [
    path(
        '',
        HomePageView.as_view(),
        name='homepage'),
    path(
        'movies/<int:pk>/',
        MovieDetailView.as_view(),
        name='detail'),
    path(
        'movies/<int:pk>/comment/',
        CommentCreateView.as_view(),
        name='comment_create'),
    path(
        'movies/browse/',
        BrowseMoviesListView.as_view(),
        name='browse_movies'),
    path(
        'nopiracy.html',
        NoPiracyTemplateView.as_view(),
        name='nopiracy')
]

movies/models.py
from django.db import models
from django.urls import reverse_lazy
from django.contrib.auth.models import User
from django.utils.text import slugify

import uuid


def generate_upload_location(instance, filename):
    random = str(uuid.uuid4())
    return '{}/{}.jpg'.format(slugify(instance.title), random)


class Movie(models.Model):
    title = models.CharField(max_length=256)
    plot = models.TextField()
    poster_image = models.ImageField(
        upload_to=generate_upload_location,
        null=True,
        blank=True)
    year = models.IntegerField()
    imdb_rating = models.FloatField(default=0)
    trailer_link = models.URLField(null=True, blank=True, max_length=512)
    genres = models.ManyToManyField(
        'Genre', related_name='movies')

    class Meta:
        ordering = ['-year']

    def __str__(self):
        return '{}({})'.format(self.title, self.year)

    def get_absolute_url(self):
        return reverse_lazy('movies:detail', kwargs={'pk': self.id})


class Genre(models.Model):
    name = models.CharField(max_length=128)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse_lazy('movies:browse_movies') +\
            '?genre={}'.format(self.id)


class Comment(models.Model):
    created_by = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name='comments')
    text = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    movie = models.ForeignKey(
        Movie, on_delete=models.CASCADE, related_name='comments')

    def __str__(self):
        return '{}... - {}'.format(self.text[:5], self.created_by.username)


class DownloadLink(models.Model):
    quality = models.CharField(max_length=16)
    link = models.CharField(max_length=512)
    movie = models.ForeignKey(
        Movie, on_delete=models.CASCADE, related_name='download_links')

    def __str__(self):
        return '{} - {}'.format(self.quality, self.movie.title)

accounts/forms.py
from django.contrib.auth.forms import UserCreationForm as DUserCreationForm
from django.contrib.auth.models import User


class UserCreationForm(DUserCreationForm):
    class Meta:
        model = User
        fields = (
            'username',
            'email',
            'password1',
            'password2',
        )

movies/forms.py
from django import forms

from .models import DownloadLink, Comment, Genre


CHOICES = [
    ('720p.BluRay', '720p.BluRay'),
    ('1080p.BluRay', '1080p.BluRay'),
    ('720p.WEBRip', '720p.WEBRip'),
    ('1080p.WEBRip', '1080p.WEBRip'),
]


class DownloadLinkForm(forms.ModelForm):
    quality = forms.ChoiceField(choices=CHOICES)

    class Meta:
        model = DownloadLink
        fields = '__all__'


class CommentForm(forms.ModelForm):

    class Meta:
        model = Comment
        fields = ('text', )


class BrowseMoviesForm(forms.Form):
    query = forms.CharField(required=False)
    genre = forms.ModelChoiceField(
        queryset=Genre.objects.all().order_by('name'),
        empty_label="Select Genre",
        required=False)

accounts/views.py
from django.contrib import messages
from django.contrib.auth import login
from django.contrib.auth.models import User
from django.views.generic import CreateView
from django.http import HttpResponseRedirect
from django.urls import reverse_lazy
from django.contrib.auth.views import LoginView as DLoginView

from .forms import UserCreationForm


class LoginView(DLoginView):
    redirect_authenticated_user = True
    template_name = 'accounts/login.html'


class RegisterView(CreateView):
    model = User
    template_name = 'accounts/register.html'
    form_class = UserCreationForm
    success_url = reverse_lazy('movies:homepage')

    def get(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            return HttpResponseRedirect(self.get_success_url())
        return super().get(request, *args, **kwargs)

    def form_valid(self, form):
        response = super().form_valid(form)
        login(self.request, self.object)
        messages.success(self.request, 'Registered Successfully!')
        return response

movies/views.py
from django.contrib import messages
from django.urls import reverse_lazy
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import (
    ListView, DetailView, CreateView, TemplateView, FormView)
from django.views.generic.list import BaseListView

from .models import Movie, Comment, Genre
from .forms import CommentForm, BrowseMoviesForm


class HomePageView(ListView):
    template_name = 'movies/homepage.html'
    context_object_name = 'movies'

    def get_queryset(self):
        return Movie.objects.all()[:8]


class MovieDetailView(DetailView):
    template_name = 'movies/detail.html'
    context_object_name = 'movie'
    queryset = Movie.objects.all()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['genres'] = self.object.genres.all()
        context['download_links'] = self.object.download_links.all()
        context['random_movies'] = Movie.objects.order_by('?')[:4]
        context['comments'] = self.object.comments.order_by(
            '-created_at').all()
        return context


class CommentCreateView(LoginRequiredMixin, CreateView):
    model = Comment
    form_class = CommentForm
    http_method_names = ['post']

    def get_success_url(self):
        pk = self.kwargs.get('pk')
        return reverse_lazy(
            'movies:detail',
            kwargs={'pk': pk})

    def form_valid(self, form):
        self.object = comment = form.save(commit=False)
        comment.created_by = self.request.user
        comment.movie = get_object_or_404(
            Movie, pk=self.kwargs.get('pk'))
        comment.save()
        return super().form_valid(form)

    def form_invalid(self, form):
        messages.error(
            self.request,
            'Comment can not be empty.',
            extra_tags='is-danger'
        )
        return HttpResponseRedirect(self.get_success_url())


class NoPiracyTemplateView(TemplateView):
    template_name = 'movies/nopiracy.html'


class BrowseMoviesListView(BaseListView, FormView):
    template_name = 'movies/browse.html'
    context_object_name = 'movies'
    http_method_names = ['get']
    form_class = BrowseMoviesForm
    paginate_by = 8
    count = 0

    def get_queryset(self):
        query = self.request.GET.get('query')
        genre_id = self.request.GET.get('genre')
        if genre_id and query:
            queryset = Genre.objects.get(
                id=genre_id).movies.filter(title__icontains=query)
        elif genre_id or query:
            if genre_id:
                queryset = Genre.objects.get(id=genre_id).movies.all()
            if query:
                queryset = Movie.objects.filter(title__icontains=query)
        else:
            queryset = Movie.objects.all().order_by('-year')[:10]
        self.count = queryset.count()
        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['count'] = self.count
        return context

templates/accounts/login.html
{% extends 'base/base_hero.html' %}

{% block content%}
<div class="columns">
  <div class="column is-4 is-offset-4">
    <div class="box has-text-black">
      <div class="subtitle has-text-centered has-text-success has-text-weight-bold">
        Login
      </div>
      <form action="" method="post">
        {% csrf_token %}
        <div class="field">
          <div class="control has-icons-left">
            <input class="input{% if form.errors %} is-danger{% endif %}"
                  type="text"
                  placeholder="Username"
                  name="username"
                  autofocus
                  required>
            <span class="icon is-small is-left">
              <i class="fas fa-user"></i>
            </span>
          </div>
        </div>
        <div class="field">
          <div class="control has-icons-left">
            <input class="input{% if form.errors %} is-danger{% endif %}"
                  type="password"
                  placeholder="Password"
                  name="password"
                  required>
            <span class="icon is-small is-left">
              <i class="fas fa-key"></i>
            </span>
          </div>
          {% if form.errors%}
          <p class="help is-danger">Username or Password incorrect.</p>
          {% endif %}
        </div>
        <div class="field">
            <div class="control">
              <button class="button is-success is-fullwidth">Login</button>
            </div>
          </div>
      </form>
    </div>
  </div>
</div>
{% endblock content %}

templates/accounts/register.html
{% extends 'base/base_hero.html' %}

{% block content%}
<div class="columns">
  <div class="column is-4 is-offset-4">
    <div class="box">
      <div class="subtitle has-text-weight-bold has-text-centered has-text-success">
        Register
      </div>
      <form action="" method="post">
        {% csrf_token %}
        {% if form.non_field_errors %}
        <div class="message is-danger">
          <div class="message-body">
            <ul class="bullet-list">
              {% for error in form.non_field_errors %}
              <li>{{ error }}</li>
              {% endfor %}
            </ul>
          </div>
        </div>
        {% endif %}
        {% for field in form %}
        <div class="field">
          <div class="control has-icons-left">
            <input
              class="input {% if field.errors %}is-danger{% endif %}"
              type="{{ field.field.widget.input_type }}"
              name="{{ field.html_name }}"
              value="{% if field.value %}{{ field.value }}{% else %}{% endif %}"
              placeholder="{{ field.label }}"
              {% if field.html_name == "username" %}autofocus{% endif %}
              required>
            <span class="icon is-small is-left">
              {% if field.html_name == "username" %}
                <i class="fas fa-user"></i>
              {% elif field.html_name == "email" %}
                <i class="fas fa-envelope"></i>
              {% elif field.html_name == "password1" or field.html_name == "password2" %}
                <i class="fas fa-key"></i>
              {% endif %}
            </span>
          </div>
          {% if field.errors %}
          <p class="help is-danger">
            {% for error in field.errors %}
              {{ error }} <br>
            {% endfor %}
          </p>
          {% endif %}
        </div>
        {% endfor %}
        <div class="field">
          <div class="control">
            <button class="button is-success is-fullwidth">Submit</button>
          </div>
        </div>
      </form>
    </div>
  </div>
</div>
{% endblock content %}

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <link rel="stylesheet" href="{% static 'css/bulma.min.css' %}">
  <link rel="stylesheet" href="{% static 'css/main.css' %}">
  <link href="https://fonts.googleapis.com/css?family=Kaushan+Script|Roboto" rel="stylesheet">
  <title>{% block title %}YIFY Clone{% endblock title %}</title>
</head>
<body>
{% block body %}
  <div class="container is-fluid">
    {% block content %}{% endblock content %}
  </div>
{% endblock body %}
</body>
</html>

templates/base/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <link rel="stylesheet" href="{% static 'css/bulma.min.css' %}">
  <link rel="stylesheet" href="{% static 'css/main.css' %}">
  <link href="https://fonts.googleapis.com/css?family=Kaushan+Script|Roboto" rel="stylesheet">
  <script src="{% static 'js/font-awesome.min.js' %}"></script>
  {% block extra_css %}
  {% endblock extra_css %}
  <title>{% block title %}YIFY Clone{% endblock title %}</title>
</head>
<body class="{% block body_classes %}has-background-black has-text-white{% endblock %}">
{% block body %}
  {% include 'include/navbar.html' %}
  {% block content %}{% endblock content %}
  {% include 'include/footer.html' %}
  {% block extra_js %}
  {% endblock extra_js %}
{% endblock body %}
  <script>
    document.addEventListener('DOMContentLoaded', function () {
      var navbarBurgers = Array.prototype.slice.call(document.querySelectorAll('.navbar-burger'), 0);
      var navbarMenu = Array.prototype.slice.call(document.querySelectorAll('.navbar-menu'), 0)[0];

      if (navbarBurgers.length > 0) {
          navbarBurgers.forEach(function (el) {
            el.addEventListener('click', function () {
              var target = el.dataset.target;
              var target = document.getElementById(target);
              el.classList.toggle('is-active');
              navbarMenu.classList.toggle('is-active');
            });
          });
        }
      }
    );
  </script>
</body>
</html>

templates/base/base_hero.html
{% extends 'base/base.html' %}

{% block body %}
{% url 'accounts:login' as login_url %}
{% url 'accounts:register' as register_url %}
{% url 'movies:homepage' as homepage_url %}
<section class="hero is-black is-fullheight">
  <div class="hero-head">
    {% include 'include/navbar.html' %}
    </header>
  </div>

  <div class="hero-body">
    <div class="container">
      {% block content %}
      {% endblock content %}
    </div>
  </div>

  <div class="hero-foot pb-10">
    <p class="is-size-65 has-text-centered">
      Created by <strong class="has-text-grey-lighter">Shakib Hossain.</strong><br>
      <a href="https://github.com/shakib609" class="has-text-grey-lighter">
        <i class="fab fa-github"></i>
      </a>
      &nbsp;
      <a href="mailto:shakib609@gmail.com" class="has-text-grey-lighter">
        <i class="fas fa-envelope"></i>
      </a>
    </p>
  </div>
</section>
{% endblock body %}

templates/include/background-overlay.html
{% if movies %}
  {% if movies|first %}
    {% with movies|first as m %}
      {% if m.poster_image %}
        <img src="/media/{{ m.poster_image}}" class="image-overlay">
      {% endif %}
    {% endwith %}
  {% endif %}
{% elif movie.poster_image %}
  <img src="/media/{{ movie.poster_image}}" class="image-overlay">
{% endif %}
<div class="gradient-overlay"></div>

templates/include/footer.html
<footer class="footer has-background-dark mt-40">
  <div class="content has-text-centered">
    <p class="is-size-65">
      Created by <strong class="has-text-grey-lighter">Shakib Hossain.</strong><br>
      <a href="https://github.com/shakib609" class="has-text-grey-lighter">
        <i class="fab fa-github"></i>
      </a>
      &nbsp;
      <a href="mailto:shakib609@gmail.com" class="has-text-grey-lighter">
        <i class="fas fa-envelope"></i>
      </a>
    </p>
  </div>
</footer>

templates/include/movie-list.html
{% load static %}
{% load mytags %}
{% if movies %}
<div class="container">
  <div class="columns is-multiline mt-10">
    {% for movie in movies %}
    <div class="column is-3 movie">
      <a href="{{ movie.get_absolute_url }}">
        <div class="image-container center-child">
            <img
              src="{% if movie.poster_image %}/media/{{ movie.poster_image }}{% else %}{% static 'images/default-poster.png' %}{% endif %}"
              alt="{{ movie.title }}"
              class="movie-poster is-relative">
            <div class="overlay has-text-centered">
              <p class="is-size-4 has-text-white" style="margin-top:200px;">
                <i class="fab fa-imdb has-text-warning"></i> {{ movie.imdb_rating }}
              </p>
              <button class="button is-success">Details</button>
            </div>
        </div>
      </a>
      <p class="is-size-6 has-text-grey-lighter has-text-centered mt-10">
        <span class="has-text-weight-bold">{{ movie.title }}</span><br>
        <small>{{ movie.year }}</small>
      </p>
    </div>
    {% endfor %}
  </div>
  {% if is_paginated %}
  {% with query=request.GET|get_item:'query' genre=request.GET|get_item:'genre' %}
  <div class="columns mt-40 mb-40">
    <div class="column center-child">
      <div class="field has-addons">
        <p class="control">
          {% if page_obj.has_previous %}
          <a class="button is-success"
            href="{% url 'movies:browse_movies' %}?page={{ page_obj.previous_page_number }}&query={{ query }}&genre={{ genre }}">
            <span class="icon is-small">
              <i class="fas fa-arrow-left"></i>
            </span>
            <span>Prev</span>
          </a>
          {% else %}
          <a class="button is-static is-success">
            <span class="icon is-small">
              <i class="fas fa-arrow-left"></i>
            </span>
            <span>Prev</span>
          </a>
          {% endif %}
        </p>
        <p class="control">
          {% if page_obj.has_next %}
          <a class="button is-success"
            href="{% url 'movies:browse_movies' %}?page={{ page_obj.next_page_number }}&query={{ query }}&genre={{ genre }}">
            <span>Next</span>
            <span class="icon is-small">
              <i class="fas fa-arrow-right"></i>
            </span>
          </a>
          {% else %}
          <a class="button is-static is-success">
            <span>Next</span>
            <span class="icon is-small">
              <i class="fas fa-arrow-right"></i>
            </span>
          </a>
          {% endif %}
        </p>
      </div>
    </div>
  </div>
  {% endwith %}
  {% endif %}
</div>
{% else %}
<div class="hero is-medium">
  <div class="hero-body">
    <h3 class="title has-text-success has-text-centered">
      No movies found!
    </h3>
    <p class="subtitle is-size-5 has-text-grey-lighter has-text-centered">
      Try something else?
    </p>
  </div>
</div>
{% endif %}

templates/include/navbar.html
{% url 'accounts:login' as login_url %}
{% url 'accounts:register' as register_url %}
{% url 'accounts:logout' as logout_url %}
{% url 'movies:homepage' as homepage_url %}
{% url 'movies:browse_movies' as browse_movies_url %}

<nav class="navbar is-black">
  <div class="container">
      <div class="navbar-brand brand">
      <a class="navbar-item has-text-success" href="{{ homepage_url }}">
        YIFY Clone
      </a>
      <div class="navbar-burger burger">
        <span></span>
        <span></span>
        <span></span>
      </div>
    </div>

    <div class="navbar-menu">
      <div class="navbar-end">
        <div class="field navbar-item">
          <form action="{% url 'movies:browse_movies' %}" method="get">
            <div class="control has-icons-left">
              <input type="text"
                name="query"
                class="input is-rounded has-background-dark is-small has-text-white">
              <span class="icon is-left">
                <fas class="fas fa-search"></fas>
              </span>
            </div>
          </form>
        </div>
        <a href="{{ homepage_url }}"
          class="navbar-item {% if request.path == homepage_url %}is-active{% endif %}">
          Home
        </a>
        <a href="{{ browse_movies_url }}"
          class="navbar-item {% if request.path == browse_movies_url %}is-active{% endif %}">
          Browse
        </a>
        {% if user.is_authenticated %}
        <a href="{{ logout_url }}" class="navbar-item">Logout</a>
        {% else %}
        <a href="{{ login_url }}"
          class="navbar-item {% if request.path == login_url %}is-active{% endif %}">
          Login
        </a>
        <a href="{{ register_url }}"
          class="navbar-item {% if request.path == register_url %}is-active{% endif %}">
          Register
        </a>
        {% endif %}
      </div>
    </div>
  </div>
</nav>

templates/movies/browse.html
{% extends 'base/base.html' %}
{% load mytags %}

{% block title %}Browse Movies | {{ block.super }}{% endblock title %}

{% block content %}
  <div class="container">
    <div class="columns is-multiline">
      <div class="column is-6 is-offset-3 mt-70 mb-40">
        <h1 class="title has-text-grey-lighter has-text-centered">
          Search
        </h1>
        <form action="" method="get">
          <div class="field">
            <div class="control is-fullwidth">
              <input class="input"
                type="text"
                name="query"
                placeholder="Search query"
                value="{{ request.GET|get_item:'query' }}"
                autofocus>
            </div>
          </div>
          <div class="field is-grouped">
            <div class="control is-expanded">
              <div class="select is-fullwidth">
                <select name="genre">
                {% with request.GET|get_item:'genre'|get_int as selected_genre %}
                  {% for x,y in form.fields.genre.choices %}
                      <option value="{{ x }}"{% if selected_genre == x %} selected{% endif %}>{{ y }}</option>
                  {% endfor %}
                {% endwith %}
                </select>
              </div>
            </div>
            <div class="control">
              <button class="button is-success" type="submit">
                Search
              </button>
            </div>
          </div>
        </form>
      </div>
    </div>
  </div>
  {% if count %}
  <div class="container mt-10 mb-30">
    <h3 class="subtitle has-text-success has-text-centered has-text-weight-bold">
      {{ count }} Movie{{ count|pluralize }} found!
    </h3>
  </div>
  {% endif %}
  {% include 'include/movie-list.html' %}
{% endblock content %}

templates/movies/detail.html
{% extends 'base/base.html' %}
{% load static %}

{% block title %}{{ movie.title }} | {{ block.super }}{% endblock title %}

{% block content %}
  {% include 'include/background-overlay.html' %}
  <div class="container mb-40 mt-40">
    <div class="columns">
      <div class="column container is-3 poster-container main-poster">
            <img
              src="{% if movie.poster_image %}/media/{{ movie.poster_image }}{% else %}{% static 'images/default-poster.png' %}{% endif %}"
              alt="{{ movie.title }}"
              class="movie-poster">
      </div>
      <div class="column">
        <h1 class="title has-text-white is-size-2">{{ movie.title }}</h1>
        <h5 class="has-text-white is-size-5 has-text-weight-bold mb-10">{{ movie.year }}</h5>
        {% if genres %}
        <div class="field is-grouped">
        {% for genre in genres %}
          <p class="control">
            <a href="{{ genre.get_absolute_url }}"
              class="button is-outlined is-transparent">
              {{ genre.name }}
            </a>
          </p>
        {% endfor %}
        </div>
        {% endif %}
        <div class="mt-40">
          <p class="is-size-6">
            Download Links:
            {% if user.is_authenticated %}
              {% if download_links %}
                {% for link in download_links %}
                <a href="{{ link.link }}" class="button is-small is-outlined is-transparent">{{ link.quality }}</a>
                {% endfor %}
              {% else %}
              <span class="is-size-7">Not Available. Check again later.</span>
              {% endif %}
            {% else %}
              <span>
                <a href="{% url 'accounts:login' %}?next={{ movie.get_absolute_url }}" class="has-text-success">Login</a>
                to view download links.
              </span>
            {% endif %}
          </p>
          <p class="mt-20 is-size-5">
            <i class="fab fa-imdb has-text-warning"></i>
            Rating &nbsp;&nbsp;: {{ movie.imdb_rating }}
            <span class="icon">
              <i class="fas fa-star has-text-success"></i>
            </span>
          </p>
        </div>
      </div>
      <div class="column is-3">
        <h4 class="subtitle has-text-white has-text-weight-bold is-size-5">
          Other Movies
        </h4>
        <div class="columns is-multiline is-mobile">
          {% for m in random_movies %}
          <div class="column is-6 poster-container other-movies">
            <a href="{{ m.get_absolute_url }}">
              <img src="/media/{{ m.poster_image }}" alt="{{ m.title }}">
            </a>
          </div>
          {% endfor %}
        </div>
      </div>
    </div>
  </div>
  <div class="container mt-70 pt-40 pb-40">
    <div class="columns">
      <div class="column">
        <h4 class="subtitle has-text-grey-lighter has-text-weight-bold">
          <i class="fab fa-wpexplorer has-text-success"></i>&nbsp;
          Plot
        </h4>
        <p class="has-text-justified">
          {{ movie.plot }}
        </p>
        <h4 class="mt-40 subtitle has-text-grey-lighter has-text-weight-bold">
          <i class="fas fa-image has-text-success"></i>&nbsp;
          Trailer
        </h4>
        <div>
        {% if movie.trailer_link %}
          <iframe width="100%" height="350"
            src="{{ movie.trailer_link }}"
            frameborder="0"
            allow="autoplay; encrypted-media"
            allowfullscreen>
          </iframe>
        {% else %}
        <p class="">
          Trailer not added yet!
        </p>
        {% endif %}
        </div>
      </div>
      <div class="column is-5">
        <h4 class="subtitle has-text-grey-lighter has-text-weight-bold">
          <i class="fas fa-comment-alt has-text-success"></i>&nbsp; {{ comments.count }} Comments
        </h4>
        <div class="comments">
          {% if comments %}
            {% for comment in comments %}
            <div class="card has-background-dark has-text-white mb-10">
              <div class="card-content">
                <div class="media">
                  <div class="media-content">
                    <p class="is-size-65 has-text-grey-lighter">
                      <span class="has-text-weight-bold">
                        {{ comment.created_by.username }}
                      </span>
                      &nbsp;
                      <small>
                        {{ comment.created_at | date }}
                      </small>
                    </p>
                    <p class="is-size-65 pt-5 has-text-justified">
                      {{ comment.text }}
                    </p>
                  </div>
                </div>
              </div>
            </div>
            {% endfor %}
          {% else %}
          <div class="card has-background-dark has-text-white">
            <div class="card-content">
              <div class="media">
                <div class="media-content">
                  <p class="is-size-6 has-text-centered">No comments yet!</p>
                </div>
              </div>
            </div>
          </div>
          {% endif %}
        </div>
        {% if user.is_authenticated %}
        <div class="card has-background-dark has-text-white border-top">
          <div class="card-content">
            <div class="media">
              <div class="media-content">
                <form action="{% url 'movies:comment_create' movie.id %}"
                  method="post">
                  {% csrf_token %}
                  <div class="field">
                    <div class="control">
                      <textarea
                        class="textarea has-background-grey-lighter"
                        placeholder="Enter your comment here"
                        rows="2"
                        name="text"
                        ></textarea>
                    </div>
                  </div>
                  <div class="field">
                    <div class="control">
                      <button class="button is-success is-fullwidth" type="submit">Submit</button>
                    </div>
                  </div>
                </form>
              </div>
            </div>
          </div>
        </div>
        {% else %}
        <div class="card has-background-dark has-text-white border-top">
          <div class="card-content">
            <div class="media">
              <div class="media-content">
                <p class="is-size-5 has-text-centered">
                  <a href="{% url 'accounts:login' %}?next={% url 'movies:detail' movie.id %}"
                    class="has-text-success has-text-weight-bold">
                    Login
                  </a>
                  to comment.
                </p>
              </div>
            </div>
          </div>
        </div>
        {% endif %}
      </div>
    </div>
  </div>
{% endblock content %}

templates/movies/homepage.html
{% extends 'base/base.html' %}

{% load static %}

{% block content %}
{% include 'include/background-overlay.html' %}
<div class="container is-fluid">
  <div class="hero is-small mb-20 mt-40">
    <div class="hero-body">
      <div class="container is-fluid has-text-centered">
        <h1 class="title has-text-white">
          YIFY Clone: quality &amp; small size movies</h1>
        <p class="font-size-09 column is-8 is-offset-2">
          Welcome to <span class="has-text-success">YIFY clone</span>, a clone of YTS/YIFY website.
          <span class="has-text-success">YIFY</span> movies are best known for the excellent BluRay quality at small file-size,
          which can be downloaded fast for free. <span class="has-text-success">YIFY</span> movies are encoded using x264 codec
          and MP4 container for best compatibility with all devices, so all users around
          the world can download <span class="has-text-success">YIFY</span> torrents and enjoy the movies.
        </p>
        <hr>
      </div>
    </div>
  </div>
  <h3 class="is-size-5 has-text-centered mb-20">
    <i class="fas fa-star has-text-warning"></i> Latest Additions
  </h3>
  {% include 'include/movie-list.html' %}
</div>
{% endblock content %}